options pageno=min nodate;
TITLE1 '';
DATA one; drop N;
DO N = 1 TO 100000;
zsq = normal(0)**2;
OUTPUT;end;
Proc Sgplot; Histogram zsq;
  density zsq  / type=normal legendlabel='Normal' lineattrs=(pattern=solid);
  density zsq  / type=kernel legendlabel='Kernel' lineattrs=(pattern=solid);
  keylegend / location=inside position=topright across=1;
  xaxis display=(nolabel);
TITLE 'Chi-Square on 1 df'; run;  
proc means mean var skewness; run;
*******************************************************************************;
DATA two; drop N zsq1 zsq2;
DO N = 1 TO 100000; zsq1 = normal(0)**2; zsq2 = normal(0)**2;
chisq2 = zsq1 + zsq2;
OUTPUT;end;
Proc Sgplot; Histogram chisq2;
  density chisq2  / type=normal legendlabel='Normal' lineattrs=(pattern=solid);
  density chisq2  / type=kernel legendlabel='Kernel' lineattrs=(pattern=solid);
  keylegend / location=inside position=topright across=1;
  xaxis display=(nolabel);
TITLE 'Chi-Square on 2 df'; run;  
proc means mean var skewness; run;
*******************************************************************************;
DATA five; drop N zsq1 --  zsq5;
DO N = 1 TO 100000; zsq1 = normal(0)**2; zsq2 = normal(0)**2;
  zsq3 = normal(0)**2; zsq4 = normal(0)**2; zsq5 = normal(0)**2;
chisq5 = sum(of zsq1 - zsq5);
OUTPUT;end;
Proc Sgplot; Histogram chisq5;
  density chisq5  / type=normal legendlabel='Normal' lineattrs=(pattern=solid);
  density chisq5  / type=kernel legendlabel='Kernel' lineattrs=(pattern=solid);
  keylegend / location=inside position=topright across=1;
  xaxis display=(nolabel);  
title 'Chi-Square on 5 df';  run;
proc means mean var skewness; run;
*******************************************************************************;
DATA ten; drop N zsq1 --  zsq10;
DO N = 1 TO 100000; zsq1 = normal(0)**2; zsq2 = normal(0)**2;
  zsq3 = normal(0)**2; zsq4 = normal(0)**2; zsq5 = normal(0)**2;
  zsq6 = normal(0)**2; zsq7 = normal(0)**2;
  zsq8 = normal(0)**2; zsq9 = normal(0)**2; zsq10 = normal(0)**2;
  chisq10 = sum(of zsq1 - zsq10);
OUTPUT;end;
Proc Sgplot; Histogram chisq10;
  density chisq10  / type=normal legendlabel='Normal' lineattrs=(pattern=solid);
  density chisq10  / type=kernel legendlabel='Kernel' lineattrs=(pattern=solid);
  keylegend / location=inside position=topright across=1;
  xaxis display=(nolabel);
title 'Chi-Square on 10 df'; run;  
proc means mean var skewness; run;
DATA fifty; drop N zsq1 --  zsq50;
DO N = 1 TO 100000; zsq1 = normal(0)**2; zsq2 = normal(0)**2;  zsq3 = normal(0)**2;
  zsq4 = normal(0)**2; zsq5 = normal(0)**2; zsq6 = normal(0)**2; zsq7 = normal(0)**2;
  zsq8 = normal(0)**2; zsq9 = normal(0)**2; zsq10 = normal(0)**2; zsq11 = normal(0)**2; zsq12 = normal(0)**2;
  zsq13 = normal(0)**2; zsq14 = normal(0)**2; zsq15 = normal(0)**2; zsq16 = normal(0)**2; zsq17 = normal(0)**2;
  zsq18 = normal(0)**2; zsq19 = normal(0)**2; zsq20 = normal(0)**2;
  zsq21 = normal(0)**2; zsq22 = normal(0)**2;  zsq23 = normal(0)**2;
  zsq24 = normal(0)**2; zsq25 = normal(0)**2; zsq26 = normal(0)**2; zsq27 = normal(0)**2;
  zsq28 = normal(0)**2; zsq29 = normal(0)**2; zsq30 = normal(0)**2; zsq31 = normal(0)**2; zsq32 = normal(0)**2;
  zsq33 = normal(0)**2; zsq34 = normal(0)**2; zsq35 = normal(0)**2; zsq36 = normal(0)**2; zsq37 = normal(0)**2;
  zsq38 = normal(0)**2; zsq39 = normal(0)**2; zsq40 = normal(0)**2;
  zsq41 = normal(0)**2; zsq42 = normal(0)**2;  zsq43 = normal(0)**2;
  zsq44 = normal(0)**2; zsq45 = normal(0)**2; zsq46 = normal(0)**2; zsq47 = normal(0)**2;
  zsq48 = normal(0)**2; zsq49 = normal(0)**2; zsq50 = normal(0)**2; 
  chisq50 = sum(of zsq1 - zsq50); 
OUTPUT;end;
Proc Sgplot; Histogram chisq50;
  density chisq50  / type=normal legendlabel='Normal' lineattrs=(pattern=solid);
  density chisq50  / type=kernel legendlabel='Kernel' lineattrs=(pattern=solid);
  keylegend / location=inside position=topright across=1;
  xaxis display=(nolabel);
title 'Chi-Square on 50 df'; run;  
proc means mean var skewness; run;
