*g1g2.sas;
***********************************************************************************;
*Illustrates use of PROC STANDARD to standardize a variable, and;
*The computation of G1, Fisher's skewness, and;
*The computation of G2, kurtosis;
***********************************************************************************;
options pageno=min nodate formdlim='-';
data EDA; infile 'C:\Users\Vati\Documents\_XYZZY\_Stats\StatData\EDA.dat'; input Y;
proc means mean skewness kurtosis N; var Y; run;
***********************************************************************************;
PROC STANDARD data=eda mean=0 std=1 out=z_scores; run;
proc means mean skewness kurtosis N; var Y; run;
***********************************************************************************;
data z34; set z_scores;
Z3=Y**3; Z4=Y**4;
proc means data=z34 noprint; var Z3 Z4; output out=sumZ34 N=N sum=sumZ3 sumZ4; run;
***********************************************************************************;
data skew; set sumz34; G1=N/(n-1)/(n-2)*sumZ3;
 G2=N*(n+1)/(n-1)/(n-2)/(n-3)*sumZ4 - 3*(n-1)*(n-1)/(n-2)/(n-3);
proc print; run;
