*Kurtosis_Beta2.sas;
*Illustrates the computation of population kurtosis;
*Using data from the handout Skewness, Kurtosis, and the Normal Curve;
***********************************************************************************;
options pageno=min nodate formdlim='-' FORMCHAR="|----|+|---+=|-/\<>*";
data A; do s=1 to 20; X=5; output; X=15; output; end;
*SS=1000, SS/N = 25, M = 10;
data ZA; set A; Z=(X-10)/5; Z4A=Z**4;
proc means mean; var Z4A; run;
***********************************************************************************;
data B; do s=1 to 20; X=5; output; X=15; output; end; do s=1 to 10; X=10; output; end;
*SS=1000, SS/N = 20;
data ZB; set B; Z=(X-10)/SQRT(20); Z4B=Z**4;
proc means mean; var Z4B; run;
***********************************************************************************;
data C; do s=1 to 20; X=5; output; X=10; output; X=15; output; end;
*SS=1000, N=60;
data ZC; set C; Z=(X-10)/SQRT(1000/60); Z4C=Z**4;
proc means mean; var Z4C; run;
***********************************************************************************;
data D; do s=1 to 10; X=5; output; X=15; output; end; do s=1 to 20; X=10; output; end;
*SS=500, SS/N = 12.5;
data ZD; set D; Z=(X-10)/SQRT(12.5); Z4D=Z**4;
proc means mean; var Z4D; run;
***********************************************************************************;
data E; do s=1 to 5; X=5; output; X=15; output; end; do s=1 to 20; X=10; output; end;
*SS=250, N=30;
data ZE; set E; Z=(X-10)/SQRT(250/30); Z4E=Z**4;
proc means mean; var Z4E; run;
***********************************************************************************;
data F; do s=1 to 3; X=5; output; X=15; output; end; do s=1 to 20; X=10; output; end;
*SS=150, N=26;
data ZF; set F; Z=(X-10)/SQRT(150/26); Z4F=Z**4;
proc means mean; var Z4F; run;
***********************************************************************************;
data G; X=5; output; X=15; output; do s=1 to 20; X=10; output; end;
*SS=50, N=22;
data ZG; set G; Z=(X-10)/SQRT(50/22); Z4G=Z**4;
proc means mean; var Z4G; run;
